version: '3'
services:
  db:
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: keycloak
  keycloak:
    volumes:
      - ./conf/server.keystore:/opt/keycloak/conf/server.keystore
    environment:
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: secret
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret

