name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.36.0
    with:
      image: ghcr.io/radiorabe/keycloak
      name: keycloak
      display-name: RaBe Keycloak
      tags: rhel9 keycloak rabe
      # needs proper multi-stage support of signed keycloak images
      cosign-verify: false
      platforms: "linux/amd64,linux/arm64"
      docker-daemon-config: |
        {
          "features": {
            "containerd-snapshotter": true
          }
        }
